### ISSUE TITLE
扩展程序没法安装

### ISSUE THREAD

**Issue by lowesyang** [SunHuawei/SourceDetector#1]
![image](https://cloud.githubusercontent.com/assets/10328169/24385586/67353288-139d-11e7-931d-794b2cc62d53.png)
如图。

**Comment by mzbac** [comment]
npm install -g bower
 bower install

**Comment by lowesyang** [comment]
![image](https://cloud.githubusercontent.com/assets/10328169/24386208/e98a969e-13a0-11e7-98ae-34918b3beb77.png)

**Comment by SunHuawei** [comment]
@yyh1102 
请尝试
`git pull`
`npm install -g bower`
`bower install`

**Comment by SunHuawei** [comment]
非常抱歉，文档没有测试好。

其实完整的安装过程应该是
1. `git clone https://github.com/SunHuawei/SourceDetector.git`
2. `npm install`
2. `bower install`
1. `gulp watch`
3. 打开Chrome设置-扩展程序
4. 点击"加载已解压的扩展程序..."
5. 选择`path/to/source-detector/app`目录

**Comment by SunHuawei** [comment]
目前版本比较粗糙，还有很多待改进的地方。接下来我会完善的部分有：

1. 上线Chrome web store
2. 完善程序、修复问题

**Comment by yyh1102** [comment]
安装成功了~感谢作者~

**Comment by lowesyang** [comment]
安装成功了，感谢作者！

**Comment by SunHuawei** [comment]
感谢反馈，谢谢大家

**Comment by sunu11** [comment]
师傅，是不是需要更新了2333，新版chrome不适配了
