### ISSUE TITLE
扩展的交互弹窗 出现异常

### ISSUE THREAD

**Issue by shuiRong** [SunHuawei/SourceDetector#2]
![image](https://user-images.githubusercontent.com/16076993/34249992-7e41c700-e676-11e7-82ad-14de6111165d.png)
点击图标之后，正常的交互弹窗一闪而过，然后显示上图这个错误的弹窗，
从Chrome扩展商店下载

**Comment by SunHuawei** [comment]
@shuiRong , 请试一下本地开发模式。Chrome Web Store正在审核新版，当前无法验证。
