### ISSUE TITLE
"Download All"只能下载一个，不能全部下载！并且也不能选择性地下。

### ISSUE THREAD

**Issue by xcmaya** [SunHuawei/SourceDetector#3]
比如说在https://www.theguardian.com/commentisfree/2018/jun/14/canada-toronto-cycling-pedestrian-deaths-cars，里面有好几个source map，但是点击download all之后，只能下载其中一个！没有办法下载所有的或者其中某几个。

谢谢！

**Comment by hkylin** [comment]
你编译的时候有报错吗？我这边有个js报错，怀疑是这个报错导致的

**Comment by SunHuawei** [comment]
@xcmaya , 点击Download All下载所有.zip文件，点击单条，下在一个.zip。点击分类标题，跳转到对应页面。
![image](https://user-images.githubusercontent.com/11191857/120443515-4b9eda80-c3b9-11eb-9b5d-4a383c2bc42e.png)

**Comment by SunHuawei** [comment]
@hkylin , 编译报错的问题可能是由于你本地的node版本是12或者更高版本，gulp@3不支持node@12, ref https://github.com/gulpjs/gulp/issues/2324。
我升级了gulp版本，已经解决了，可以用pull下代码。
