### ISSUE TITLE
ReferenceError: primordials is not defined in node

### ISSUE THREAD

**Issue by Becivells** [SunHuawei/SourceDetector#5]
执行到gulp报错解决方法如下

Create a npm-shrinkwrap.json file containing this:
```
{
  "dependencies": {
    "graceful-fs": {
      "version": "4.2.3"
    }
  }
}
```
Commit this npm-shrinkwrap.json file. And then execute npm install which will update the npm-shrinkwrap.json file.

link:https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node

**Comment by hkylin** [comment]
你用node 11版本试试，这边测试OK ，12不行

**Comment by SunHuawei** [comment]
@Becivells , 感谢提供方法。已经通过升级gulp解决。请pull最新代码。
